name: Cosmos scrape -> gallery.json
on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"   # every hour

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed for gh-pages push
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Scrape Cosmos
        env:
          COSMOS_URL: ${{ vars.COSMOS_URL }}
        run: npm run scrape

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
